name: Crowdin Curriculum Upload
'on':
  workflow_dispatch: null
  schedule:
  - cron: 30 11 * * *
jobs:
  i18n-upload-curriculum-files:
    name: Learn
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Files
      uses: actions/checkout@v2
    - name: Generate Crowdin Config
      uses: freecodecamp/crowdin-action@main
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
        CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        PLUGIN: generate-config
        PROJECT_NAME: curriculum
    - name: Crowdin Upload
      uses: crowdin/github-action@master
      with:
        upload_sources: true
        upload_translations: false
        auto_approve_imported: false
        import_eq_suggestions: false
        download_translations: false
        create_pull_request: false
        config: ./crowdin-config.yml
        base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
    - name: Remove deleted files
      uses: freecodecamp/crowdin-action@main
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
        CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        PLUGIN: remove-deleted-files
        FILE_PATHS: '["curriculum/challenges/english", "curriculum/dictionaries/english"]'
    - name: Hide Non-Translated Strings
      uses: freecodecamp/crowdin-action@main
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
        CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        PLUGIN: hide-curriculum-strings
    - name: Hide a String
      uses: freecodecamp/crowdin-action@main
      env:
        CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
        PLUGIN: hide-string
        FILE_NAME: basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md
        STRING_CONTENT: Here's a <a href="https://www.freecodecamp.org" target="_blank"
          mark="crwd-mark">link to www.freecodecamp.org</a> for you to follow.
    - name: Unhide Title of Use && For a More Concise Conditional
      uses: freecodecamp/crowdin-action@main
      env:
        CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
        PLUGIN: unhide-string
        FILE_NAME: react/use--for-a-more-concise-conditional.md
        STRING_CONTENT: Use &amp;&amp; for a More Concise Conditional
